[project]
name = "swoyo-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.5",
    "pytest-mock>=3.14.0",
    "toml>=0.10.2",
    "tomli>=2.2.1",
]
